version : '3'
services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: ffthh
      MYSQL_PASSWORD: example
      MYSQL_DATABASE: ffthh
    ports:
      - "3306:3306"
    volumes:
      - "./scripts/schema.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./scripts/data.sql:/docker-entrypoint-initdb.d/2.sql"
#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8080:8080